apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxconsole
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluxconsole
  template:
    metadata:
      labels:
        app: fluxconsole
    spec:
      containers:
        - name: fluxconsole
          image: ghcr.io/ommkwn/fluxconsole:1.0.0
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: fluxconsole
  namespace: flux-system
spec:
  selector:
    app: fluxconsole
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
